prometheus:
  prometheusSpec:
    additionalAlertManagerConfigs:
      - static_configs:
          - targets: [
            "lab-argocd-alertmanager.alertmanager.svc.cluster.local:9093"
          ]
        scheme: http