apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-config-secret
  namespace: monitoring
  labels:
    app.kubernetes.io/name: alertmanager
type: Opaque
data:
  config.yaml: Z2xvYmFsOgogIHJlc29sdmVfdGltZW91dDogMW0Kcm91dGU6CiAgcmVjZWl2ZXI6ICdkZWZhdWx0LXJlY2VpdmVyJwogIGdyb3VwX2J5OiBbJ2FsZXJ0bmFtZSddCiAgZ3JvdXBfd2FpdDogMW0KICBncm91cF9pbnRlcnZhbDogNW0KICByZXBlYXRfaW50ZXJ2YWw6IDEyaAoKcmVjZWl2ZXJzOgotIG5hbWU6ICdkZWZhdWx0LXJlY2VpdmVyJw==
  default.tmpl: e3sgZGVmaW5lICJvcHNnZW5pZV90aXRsZSIgfX0KW1BST01FVEhFVVNdIHt7IC5Db21tb25Bbm5vdGF0aW9ucy5tZXNzYWdlfX0gLSB7eyAuQ29tbW9uTGFiZWxzLnNldmVyaXR5IHwgdG9VcHBlciB9fQp7eyBlbmQgfX0KCnt7IGRlZmluZSAiY3VzdG9tX3RpdGxlIiB9fQpbe3sgLlN0YXR1cyB8IHRvVXBwZXIgfX17eyBpZiBlcSAuU3RhdHVzICJmaXJpbmciIH19Ont7IC5BbGVydHMuRmlyaW5nIHwgbGVuIH19e3sgZW5kIH19XSB7eyAuQ29tbW9uTGFiZWxzLmFsZXJ0bmFtZSB9fQp7eyBlbmQgfX0KCnt7IGRlZmluZSAiY3VzdG9tX3NsYWNrX21lc3NhZ2UiIH19CipTdW1tYXJ5Oioge3sgLkNvbW1vbkFubm90YXRpb25zLnN1bW1hcnkgfX0gLSBge3sgLkNvbW1vbkxhYmVscy5zZXZlcml0eSB8IHRvVXBwZXIgfX1gCnt7IHJhbmdlIC5BbGVydHMgfX0KICAqRGVzY3JpcHRpb246KiB7eyAuQW5ub3RhdGlvbnMubWVzc2FnZSB9fQogICpEZXRhaWxzOioKICB7eyByYW5nZSAuTGFiZWxzLlNvcnRlZFBhaXJzIH19IOKAoiAqe3sgLk5hbWUgfCB0aXRsZSB9fToqIGB7eyAuVmFsdWUgfX1gCiAge3sgZW5kIH19Cnt7IGVuZCB9fQoKe3sgZW5kIH19Cg==
